license = "MIT"
loaderVersion = "[36,)"
modLoader = "javafml"
[[mods]]
displayName = "DMCLoot"
modId = "dmcloot"
version = "1.16.5"
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dmcloot"
authors = "shiroroku(elise)"
credits = "amo"
description = '''
Adds various RPG-like affixes to tools, weapons, and armor!
'''
[[dependencies.dmcloot]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "[36,)"
[[dependencies.dmcloot]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.16.5,1.17)"
