license = "MIT"
loaderVersion = "[36,)"
modLoader = "javafml"
[[mods]]
displayName = "DMCLoot"
modId = "dmcloot"
version = "${file.jarVersion}"
#logoFile="dmcloot.png"
authors = "Amo, shiroroku(elise)"
credits = ""
description = '''
beepboop description beep
'''
[[dependencies.dmcloot]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "[36,)"
[[dependencies.dmcloot]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.16.5,1.17)"
